This notebook is a Numpy Practice, built based on the Youtube channel - [Nicholas Renotte](https://www.youtube.com/watch?v=uRsE5WGiKWo&list=PLgNJO2hghbmjpjt9sa2POi4U0a1-GGTlj&index=1).

##CREATE

In [1]:
import numpy as np

In [5]:
data = np.random.rand(2,3,4)
zeros = np.zeros((2,2,2))
full = np.full((2,2,2),9)
ones = np.ones((2,2,2))

In [3]:
data

array([[[0.63560618, 0.337079  , 0.51096135, 0.72318385],
        [0.50938869, 0.79939609, 0.54849903, 0.00122319],
        [0.04299054, 0.03761445, 0.09238669, 0.31037061]],

       [[0.75865056, 0.43301534, 0.35790922, 0.96112821],
        [0.74211852, 0.50740904, 0.33175292, 0.84995526],
        [0.50283183, 0.7574044 , 0.69344498, 0.73567099]]])

In [6]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [7]:
full

array([[[9, 9],
        [9, 9]],

       [[9, 9],
        [9, 9]]])

In [8]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [9]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [10]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [12]:
type(arr)

numpy.ndarray

##READ

In [14]:
#Attributes

shape = data.shape
size = data.size
types = data.dtype

In [15]:
shape

(2, 3, 4)

In [16]:
size

24

In [17]:
types

dtype('float64')

In [25]:
#Slicers

arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
single_val = data[0][0][0]

In [19]:
arr

array([[0.1630594 , 0.42974848, 0.86125996, 0.45838427],
       [0.41414831, 0.77807301, 0.3009982 , 0.79019797],
       [0.55894303, 0.14278404, 0.73287429, 0.8346951 ]])

In [22]:
slicer

array([[0.1630594 , 0.42974848, 0.86125996, 0.45838427],
       [0.41414831, 0.77807301, 0.3009982 , 0.79019797]])

In [23]:
reverse

array([[0.76036688, 0.738468  , 0.56353828, 0.79430163],
       [0.35631414, 0.13346503, 0.77943955, 0.10997729],
       [0.00162613, 0.27712216, 0.58519322, 0.34711659]])

In [26]:
single_val

0.16305939804743452

##UPDATE

In [27]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [28]:
#Basic Math Functions

add = np.add(list1,list2)
sub = np.subtract(list1,list2)
mult = np.multiply(list1,list2)
div = np.divide(list1,list2)
dot = np.dot(list1,list2)

In [32]:
print(list1)
print(list2)

[0.6598603  0.97912222 0.08105853 0.60221976 0.98978995 0.4301138
 0.73190236 0.97233437 0.20595744 0.20242901]
[0.32823587 0.76387814 0.57089815 0.66375536 0.50114553 0.07090031
 0.69810914 0.52071063 0.84966518 0.81372919]


In [29]:
add

array([0.98809617, 1.74300036, 0.65195668, 1.26597512, 1.49093548,
       0.50101411, 1.4300115 , 1.49304501, 1.05562262, 1.01615819])

In [30]:
sub

array([ 0.33162443,  0.21524408, -0.48983963, -0.06153561,  0.48864442,
        0.35921349,  0.03379322,  0.45162374, -0.64370774, -0.61130018])

In [33]:
mult

array([0.21658982, 0.74793006, 0.04627616, 0.39972659, 0.49602881,
       0.0304952 , 0.51094773, 0.50630485, 0.17499487, 0.16472239])

In [34]:
div

array([2.01032355, 1.28177803, 0.14198422, 0.90729174, 1.97505492,
       6.06645842, 1.04840679, 1.86732191, 0.24239835, 0.24876705])

In [35]:
dot

3.2940164781812737

In [36]:
#Stat Functions

sqrt = np.sqrt(25)
ab = np.abs(-25)
power = np.power(2,5)
log = np.log(25)
min = np.min(list1)
max = np.max(list2)

In [37]:
sqrt

5.0

In [38]:
ab

25

In [39]:
power

32

In [40]:
log

3.2188758248682006

In [41]:
min

0.08105852644426059

In [42]:
max

0.8496651796582247

In [43]:
data

array([[[0.1630594 , 0.42974848, 0.86125996, 0.45838427],
        [0.41414831, 0.77807301, 0.3009982 , 0.79019797],
        [0.55894303, 0.14278404, 0.73287429, 0.8346951 ]],

       [[0.76036688, 0.738468  , 0.56353828, 0.79430163],
        [0.35631414, 0.13346503, 0.77943955, 0.10997729],
        [0.00162613, 0.27712216, 0.58519322, 0.34711659]]])

In [44]:
data[0][0][0] = 900

In [45]:
data

array([[[9.00000000e+02, 4.29748476e-01, 8.61259962e-01, 4.58384266e-01],
        [4.14148314e-01, 7.78073007e-01, 3.00998198e-01, 7.90197974e-01],
        [5.58943025e-01, 1.42784043e-01, 7.32874292e-01, 8.34695101e-01]],

       [[7.60366883e-01, 7.38467999e-01, 5.63538281e-01, 7.94301627e-01],
        [3.56314144e-01, 1.33465032e-01, 7.79439546e-01, 1.09977289e-01],
        [1.62613294e-03, 2.77122163e-01, 5.85193218e-01, 3.47116590e-01]]])

In [47]:
data.sort()

In [48]:
data

array([[[4.29748476e-01, 4.58384266e-01, 8.61259962e-01, 9.00000000e+02],
        [3.00998198e-01, 4.14148314e-01, 7.78073007e-01, 7.90197974e-01],
        [1.42784043e-01, 5.58943025e-01, 7.32874292e-01, 8.34695101e-01]],

       [[5.63538281e-01, 7.38467999e-01, 7.60366883e-01, 7.94301627e-01],
        [1.09977289e-01, 1.33465032e-01, 3.56314144e-01, 7.79439546e-01],
        [1.62613294e-03, 2.77122163e-01, 3.47116590e-01, 5.85193218e-01]]])

In [50]:
print(data.shape)

(2, 3, 4)


In [51]:
data = data.reshape((2,2,-1))

In [52]:
data.shape

(2, 2, 6)

In [53]:
zeros = np.zeros(9)

In [54]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
vals = [3,4]
zeros = np.append(zeros,vals)

In [56]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 4.])

In [57]:
zeros = np.insert(zeros, 2, vals)

In [58]:
zeros

array([0., 0., 3., 4., 0., 0., 0., 0., 0., 0., 0., 3., 4.])

#DELETE

In [59]:
data

array([[[4.29748476e-01, 4.58384266e-01, 8.61259962e-01, 9.00000000e+02,
         3.00998198e-01, 4.14148314e-01],
        [7.78073007e-01, 7.90197974e-01, 1.42784043e-01, 5.58943025e-01,
         7.32874292e-01, 8.34695101e-01]],

       [[5.63538281e-01, 7.38467999e-01, 7.60366883e-01, 7.94301627e-01,
         1.09977289e-01, 1.33465032e-01],
        [3.56314144e-01, 7.79439546e-01, 1.62613294e-03, 2.77122163e-01,
         3.47116590e-01, 5.85193218e-01]]])

In [61]:
np.delete(data, 0, axis=1)

array([[[0.77807301, 0.79019797, 0.14278404, 0.55894303, 0.73287429,
         0.8346951 ]],

       [[0.35631414, 0.77943955, 0.00162613, 0.27712216, 0.34711659,
         0.58519322]]])

In [62]:
np.save("new_array", data)

In [63]:
test = np.load("new_array.npy")

In [64]:
test

array([[[4.29748476e-01, 4.58384266e-01, 8.61259962e-01, 9.00000000e+02,
         3.00998198e-01, 4.14148314e-01],
        [7.78073007e-01, 7.90197974e-01, 1.42784043e-01, 5.58943025e-01,
         7.32874292e-01, 8.34695101e-01]],

       [[5.63538281e-01, 7.38467999e-01, 7.60366883e-01, 7.94301627e-01,
         1.09977289e-01, 1.33465032e-01],
        [3.56314144e-01, 7.79439546e-01, 1.62613294e-03, 2.77122163e-01,
         3.47116590e-01, 5.85193218e-01]]])